Classify the email using the binary classification method. Email Spam detection has two
states: a) Normal State – Not Spam, b) Abnormal State – Spam. Use K-Nearest Neighbors and
Support Vector Machine for classification. Analyze their performance.
Dataset link: The emails.csv dataset on the Kaggle
https://www.kaggle.com/datasets/balaka18/email-spam-classification-dataset-csv

In [19]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [20]:
df = pd.read_csv('emails.csv')
df

Email No.  the  to  ect  and  for  of    a  you  hou  ...  connevey  \
0        Email 1    0   0    1    0    0   0    2    0    0  ...         0   
1        Email 2    8  13   24    6    6   2  102    1   27  ...         0   
2        Email 3    0   0    1    0    0   0    8    0    0  ...         0   
3        Email 4    0   5   22    0    5   1   51    2   10  ...         0   
4        Email 5    7   6   17    1    5   2   57    0    9  ...         0   
...          ...  ...  ..  ...  ...  ...  ..  ...  ...  ...  ...       ...   
5167  Email 5168    2   2    2    3    0   0   32    0    0  ...         0   
5168  Email 5169   35  27   11    2    6   5  151    4    3  ...         0   
5169  Email 5170    0   0    1    1    0   0   11    0    0  ...         0   
5170  Email 5171    2   7    1    0    2   1   28    2    0  ...         0   
5171  Email 5172   22  24    5    1    6   5  148    8    2  ...         0   

      jay  valued  lay  infrastructure  military  allowing  ff  dry  \
0       0       0    0               0         0         0   0    0   
1       0       0    0               0         0         0   1    0   
2       0       0    0               0         0         0   0    0   
3       0       0    0               0         0         0   0    0   
4       0       0    0               0         0         0   1    0   
...   ...     ...  ...             ...       ...       ...  ..  ...   
5167    0       0    0               0         0         0   0    0   
5168    0       0    0               0         0         0   1    0   
5169    0       0    0               0         0         0   0    0   
5170    0       0    0               0         0         0   1    0   
5171    0       0    0               0         0         0   0    0   

      Prediction  
0              0  
1              0  
2              0  
3              0  
4              0  
...          ...  
5167           0  
5168           0  
5169           1  
5170           1  
5171           0  

[5172 rows x 3002 columns]

In [21]:
df.drop(['Email No.'],axis=1,inplace=True)
X = df.drop(['Prediction'],axis = 1)
y = df['Prediction']

In [22]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import scale
X = scale(X)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 42)

In [23]:
X_train

array([[ 0.03060621, -0.22951624, -0.2229717 , ..., -0.0562853 ,
        -0.32904848, -0.07097072],
       [-0.56544926, -0.64908256, -0.2938948 , ..., -0.0562853 ,
        -0.32904848, -0.07097072],
       [ 0.20090777, -0.12462466, -0.2229717 , ..., -0.0562853 ,
         0.39039297, -0.07097072],
       ...,
       [-0.56544926, -0.64908256, -0.2938948 , ..., -0.0562853 ,
        -0.32904848, -0.07097072],
       [-0.3951477 ,  0.50472481, -0.2938948 , ..., -0.0562853 ,
         0.75011369, -0.07097072],
       [-0.30999692, -0.64908256, -0.2938948 , ..., -0.0562853 ,
        -0.32904848, -0.07097072]])

In [24]:
y_train

1023    0
4587    0
4415    0
4863    1
4901    0
       ..
4426    0
466     0
3092    0
3772    1
860     1
Name: Prediction, Length: 3620, dtype: int64

In [25]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=7)

knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)

In [28]:
print("Prediction",y_pred)

Prediction [0 0 1 ... 1 1 1]


In [29]:
y_test

1566    0
1988    0
1235    1
3276    0
3438    0
       ..
3558    0
2298    0
1519    0
1740    0
1700    1
Name: Prediction, Length: 1552, dtype: int64

In [30]:
from sklearn import metrics
metrics.accuracy_score(y_test, y_pred)

0.8009020618556701

In [31]:
metrics.confusion_matrix(y_test, y_pred)

array([[804, 293],
       [ 16, 439]])

In [33]:
from sklearn.svm import SVC
# cost C = 1
model = SVC(C = 1)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [34]:
y_pred

array([0, 0, 1, ..., 0, 0, 1])

In [35]:
metrics.accuracy_score(y_test, y_pred)

0.9381443298969072

In [36]:
metrics.confusion_matrix(y_test, y_pred)

array([[1091,    6],
       [  90,  365]])